project_id            = "keen-vision-467717-r4"
billing_account       = "018233-E6C933-79B0AE"
region                = "us-central1"
team                  = "vance"
org_id                = "102676662666"
folder_id             = "102676662666"
image_bucket          = "rag-image-corpus"
image_bucket_location = "us-central1"
cmek                  = ""
group_email           = ""

custom_service_account_email = "ravance@gmail.com"
iam_sql_user                 = "ravance@gmail.com"